### ISSUE TITLE
errors with the code 

### ISSUE THREAD

**Issue by vandan-revanur** [BlaiseGratton/take_note#1]
These lines of the code produces errors in my system. I'm running Ubuntu 14.04. 
user = get_object_or_404(User, username=username)
try:
    with database.transaction():
        Relationship.create(
                from_user=get_current_user(),
                to_user=user)
except IntegrityError:
    pass

The errors produced are:

Traceback (most recent call last):
  File "app.py", line 64, in <module>
    user = get_object_or_404(User, username=username)
NameError: name 'get_object_or_404' is not defined

Traceback (most recent call last):
  File "app.py", line 67, in <module>
    Relationship.create(
NameError: name 'Relationship' is not defined

After commenting those lines the app works fine. Also there is no route written for the root web address in app.py, ie http://0.0.0.0:8000/

**Comment by BlaiseGratton** [comment]
vandan-r -  thanks for the clone. There's nothing wrong with your system,
as it's not working on mine either - I had to push this (unfinished)
project up to github since I was wiping my computer. I'm still working out
a user login (for the root route) etc. I should maybe have an MVP of this
up in a couple weeks, I'll let you know when that occurs. Still learning
the ropes of how to integrate peewee with flask.

On Sun, Feb 15, 2015 at 7:21 AM, vandan-r notifications@github.com wrote:

> These lines of the code produces errors in my system. I'm running Ubuntu
> 14.04.
> user = get_object_or_404(User, username=username)
> try:
> with database.transaction():
> Relationship.create(
> from_user=get_current_user(),
> to_user=user)
> except IntegrityError:
> pass
> 
> The errors produced are:
> 
> Traceback (most recent call last):
> File "app.py", line 64, in
> user = get_object_or_404(User, username=username)
> NameError: name 'get_object_or_404' is not defined
> 
> Traceback (most recent call last):
> File "app.py", line 67, in
> Relationship.create(
> NameError: name 'Relationship' is not defined
> 
> After commenting those lines the app works fine. Also there is no route
> written for the root web address in app.py, ie http://0.0.0.0:8000/
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/BlaiseGratton/take_note/issues/1.

## 

Blaise Gratton
Classical Studies
267.496.1043

**Comment by BlaiseGratton** [comment]
The app is now nearly finished other than styling and a couple advanced features, so I'll mark this issue as closed.
